services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8080:80"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=laravel_api
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=secret_password
            - CACHE_DRIVER=redis
            - SESSION_DRIVER=redis
            - QUEUE_CONNECTION=redis
            - REDIS_HOST=redis
        depends_on:
            - db
            - redis
        networks:
            - laravel_network

    db:
        image: postgres:16-alpine
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel_api
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret_password
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    redis:
        image: redis:7-alpine
        container_name: laravel_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: laravel_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin_password
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
